### ISSUE TITLE
Extension Installation failed

### ISSUE THREAD

**Issue by bananastalktome** [TheresNoBox/Brackets-Ruby#1]
When trying to install this extension in sprint 26 of Brackets on OSX (10.8.4), I enter the URL "https://github.com/TheresNoBox/Brackets-Ruby" and it starts trying to install the package, but fails and I get the message:

```
Installation failed.
TheresNoBox.Brackets-Ruby is an invalid package name
```

I was successfully able to install a different extension listed in the Brackets list of extensions page (https://github.com/aonic/brackets-QuickOpenPHP is the one I tried), if that helps.

**Comment by bcentinaro** [comment]
Thanks, the package meta data is still under development. It seems like the brackets doesn't like their own suggested format. Should have it patched up shortly.

Also thanks for reporting.

**Comment by bcentinaro** [comment]
Changed around package meta data, and confirmed installation with sprint-26 (on OSX).
