### ISSUE TITLE
rails tags closed divs

### ISSUE THREAD

**Issue by davidfabreguette** [TheresNoBox/Brackets-Ruby#2]
I have a weird behavior when i'm in a erb view,
when I type in "<%%>" it adds automatically "</%>" afterward.
I guess the problem is rails tags are considered the same as any other HTML tag.
Any idea how to solve this ?

**Comment by kompuser** [comment]
I think the trick is to uncheck the following menu item : Edit > Auto Close Braces , within Brackets app.
